# coverity
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "CtjbyXy6/hMBjqjxQPV5BnpseoJ3QvnGK367bAadtFnUbYYOQm+GZEkKS6N9e6023EICrZH2SQsicelEsb3hVL3KjuipfYhu5Rh1cwa8vlzI2zNP7/qkcdwXch8xMJgkh2iPQ8iQz/V65a6s1VM6l+ZDEZNcl4W3jxfAZy/dBLwCuNbdQ8ve6KCAjTeLGw2DaRTVvWCUziaE/OXjPscWY9Vn8QiLmJj29dwGHV5xLeRzPbzXCily6hW+RhgpyIYA/CC77HL1BlUPW3TG0YodmFe808bphJL0WTj00KsfsblVqC3D0A1jRIhK6TShsAKSdXypPWl0+EiJSYyxM4aiXXwMHqABn0L4rprk+SldB7rLABKPzOiCVAQIMl/8/l8WTaB1XhRtr3Jx0ibA4u2gGxhkMJAnQdlPiTto4j0HvWiyuWaIpIjrDpq2YAeVOvDoK0N21X3rQSVol94uaoAW0Y4H2jIOUZs3DCwqpioDSIuYxjtCI4YhsjrrGXURT3vyTOOXoUpdckNdUbMTWUJVREnhsvQuwTECzB74C37RW6P6WR5YWI8NxBe5zdtSApg5Fjg7KM/T+ko/h91vtGbndMW0PFR86b1OHYwyuv57VemcaGLeY04Ph+EJttrK/uTZ6Cm02pIFAMzH0XChEdVwt8R0pnLLqs2HNoo+ViwR56w="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ChristofDubs/pyrotation"
      description: "Numpy-based rotation library"
    notification_email: christof.dubs@gmx.ch
    build_command_prepend:
    build_command:
    branch_pattern: coverity_scan

# unit tests
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
cache: pip
install:
script:
  - python test.py